#!/usr/bin/ruby 

url = "http://www.carlaradio.net/thesystem/systemdetail.php?sysid="
out = ""
(2..36).each { | i | 
#  puts "curl '#{url}#{"%02d" % i}'"
  out = `curl '#{url}#{"%02d" % i}'`
   callsign = out.match(/[A-Z]{1,2}[0-9][A-Z]{1,3}/)
   out =~ /System [0-9]{1,2}:(.*)\</
   puts i.to_s + "," + callsign.to_s + "," + $1.to_s
#  exit
}

#curl "http://www.carlaradio.net/thesystem/systemdetail.php?sysid=02" | grep '[A-Z][0-9][A-Z][A-Z]'

